(()=>{
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let records=null,busy=false;
 const status=s=>$('adminStatus').textContent=s;
 const identity=id=>esc(records.mr_profiles.find(p=>p.user_id===id)?.display_name||'Collector')+' · '+esc(records.contacts[id]?.email||id);
 function cardList(ids){return ids.map(id=>{const p=records.mr_pulls.find(p=>p.id===id),c=records.mr_inventory.find(c=>c.id===p?.inventory_id);return p?`${esc(p.title)} · SKU ${esc(c?.sku||p.inventory_id)} · ${esc(p.kind)}`:esc(id);}).join('<br>');}
 async function load(){if(busy)return;busy=true;try{records=await MarzAccount.api('admin');render();status('Updated '+new Date().toLocaleTimeString()+'. Tables show the latest 500 records; contact details are limited to the latest 100 collectors.');}catch(e){status(e.message);}finally{busy=false;}}
 function render(){
  const pending=records.mr_shipping.filter(s=>s.status!=='shipped');$('fulfillmentCount').textContent=pending.length;$('fulfillmentBadge').textContent=pending.length?`${pending.length} SHIPPING REQUEST${pending.length===1?'':'S'} NEED ATTENTION`:'No shipping requests waiting';
  $('fulfillmentQueue').innerHTML=pending.map(s=>`<article class="admin-item"><h3>${identity(s.user_id)}</h3><p>Request ${esc(s.id)} · ${esc(s.status)} · ${esc(s.fee_status)}</p><p>${cardList(s.pull_ids)}</p><p>${['name','line1','line2','city','region','postal','country'].map(k=>esc(s.address[k])).filter(Boolean).join(' · ')}</p><form data-fulfillment="${esc(s.id)}"><div class="subgrid"><label>Carrier<input name="carrier" value="${esc(s.carrier)}" maxlength="100"></label><label>Tracking number<input name="tracking" value="${esc(s.tracking)}" maxlength="150"></label><label>Shipping fee<select name="fee_status"><option value="quote_needed" ${s.fee_status==='quote_needed'?'selected':''}>Quote needed / unpaid</option><option value="paid" ${s.fee_status==='paid'?'selected':''}>Paid — confirmed externally</option><option value="waived" ${s.fee_status==='waived'?'selected':''}>Owner waives shipping fee</option></select></label><label>Fulfillment<select name="status"><option value="packing">Packing</option><option value="shipped">Shipped</option></select></label></div><label>Internal notes<textarea name="notes" maxlength="1000">${esc(s.notes)}</textarea></label><button class="btn primary">Save fulfillment</button></form></article>`).join('')||'<p class="sub">No requests to fulfill. New requests appear here automatically while this dashboard is open.</p>';
  $('pullLedger').innerHTML=records.mr_pulls.map(p=>{const c=records.mr_inventory.find(c=>c.id===p.inventory_id);return `<tr><td>${identity(p.user_id)}</td><td>${esc(p.title)}<br><small>SKU ${esc(c?.sku||p.inventory_id)}</small></td><td>${esc(p.kind)} · $${p.tier_cents/100}</td><td>${esc(p.shipping_status)}</td></tr>`;}).join('')||'<tr><td colspan="4">No real card pulls yet. Demo openings do not create fulfillment records.</td></tr>';
  $('rewardLedger').innerHTML=records.mr_packs.filter(p=>p.kind==='bonus').map(p=>`<tr><td>${identity(p.user_id)}</td><td>${p.milestone} paid openings</td><td>$1 bonus · ${esc(p.status)}</td></tr>`).join('')||'<tr><td colspan="3">No paid milestones reached yet.</td></tr>';
  $('inventoryLedger').innerHTML=records.mr_inventory.map(c=>`<tr><td>${esc(c.sku)}</td><td>${esc(c.title)}</td><td>$${c.tier_cents/100} · ${esc(c.pool)}</td><td>${esc(c.status)}</td></tr>`).join('')||'<tr><td colspan="4">Add the exact physical cards you have on hand before sales open.</td></tr>';
  $('inventoryCount').textContent=records.mr_inventory.filter(c=>c.status==='available').length;
  $('memberCount').textContent=records.mr_memberships.filter(m=>m.status==='active'&&Date.parse(m.paid_until)>Date.now()).length;
  $('shipmentHistory').innerHTML=records.mr_shipping.filter(s=>s.status==='shipped').map(s=>`<p>${identity(s.user_id)} · ${esc(s.carrier)} ${esc(s.tracking)} · ${s.pull_ids.length} cards</p>`).join('')||'<p class="micro">No shipments recorded.</p>';
  $('reviewQueue').innerHTML=records.mr_audit.filter(a=>a.action==='refund_review_required').map(a=>`<p>REFUND REVIEW · ${esc(a.record_id)} · ${esc(JSON.stringify(a.details))}</p>`).join('')||'<p class="micro">No payment refunds flagged for review.</p>';
 }
 window.renderMarzAdmin=(isAdmin,user)=>{if(!isAdmin){$('adminContent').hidden=true;$('adminGate').hidden=false;$('adminGateText').textContent=user?'This account does not have administrator access. Owner approval is required before assigning the role.':'Sign in with your approved owner account. Customer accounts cannot view inventory or shipping addresses.';return;}$('adminGate').hidden=true;$('adminContent').hidden=false;load();};
 $('adminRefresh').onclick=load;
 $('inventoryForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const card=Object.fromEntries(new FormData(e.target));await MarzAccount.api('inventory',{card});e.target.reset();await load();status('Inventory card saved. Keep the physical card labeled with its SKU.');}catch(e){status(e.message);}finally{b.disabled=false;}});
 $('fulfillmentQueue').addEventListener('submit',async e=>{e.preventDefault();const id=e.target.dataset.fulfillment;if(!id)return;const b=e.target.querySelector('button');b.disabled=true;try{const fields=Object.fromEntries(new FormData(e.target));if(fields.status==='shipped'&&!confirm('Confirm you have handed this shipment to the carrier and entered its real tracking number.'))return;await MarzAccount.api('fulfill',{order_id:id,...fields});await load();}catch(e){status(e.message);}finally{b.disabled=false;}});
 setInterval(()=>{if(!document.hidden&&!$('adminContent').hidden)load();},30000);
})();
